// lib/encyclopedia/starterSneakers.ts
export type SneakerStarterEntry = {
    slug: string;
    name: string;
    brand: string;
    family?: string;
    silhouette?: string;
    firstRelease?: string;
    designer?: string;
    retailPrice?: string;
    tier: 1 | 2 | 3;
    tagline: string;
    relatedSlugs?: string[];
  };
  
  export const starterSneakers: SneakerStarterEntry[] = [
    {
      slug: "air-force-1",
      name: "Nike Air Force 1",
      brand: "Nike",
      family: "Air Force",
      silhouette: "Low",
      firstRelease: "1982",
      designer: "Bruce Kilgore",
      retailPrice: "$90–$110",
      tier: 1,
      tagline: "The all-time staple that moved from basketball to global streetwear icon.",
      relatedSlugs: ["air-jordan-1", "dunk-low", "air-max-90"],
    },
    {
      slug: "air-jordan-1",
      name: "Air Jordan 1",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High / Mid / Low",
      firstRelease: "1985",
      designer: "Peter Moore",
      retailPrice: "$100–$180",
      tier: 1,
      tagline: "The silhouette that changed basketball, streetwear, and sneaker culture forever.",
      relatedSlugs: ["air-jordan-4", "air-force-1", "dunk-low"],
    },
    {
      slug: "air-jordan-4",
      name: "Air Jordan 4",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1989",
      designer: "Tinker Hatfield",
      retailPrice: "$210–$225",
      tier: 1,
      tagline: "A heritage grail known for visible tech, cultural weight, and strong resale energy.",
      relatedSlugs: ["air-jordan-1", "air-jordan-3", "air-jordan-11"],
    },
    {
      slug: "dunk-low",
      name: "Nike Dunk Low",
      brand: "Nike",
      family: "Dunk",
      silhouette: "Low",
      firstRelease: "1985",
      designer: "Peter Moore",
      retailPrice: "$110–$135",
      tier: 1,
      tagline: "A versatile low-top with strong crossover appeal from skate, streetwear, and resale.",
      relatedSlugs: ["sb-dunk-low", "air-force-1", "air-jordan-1"],
    },
    {
      slug: "sb-dunk-low",
      name: "Nike SB Dunk Low",
      brand: "Nike SB",
      family: "SB Dunk",
      silhouette: "Low",
      firstRelease: "2002",
      retailPrice: "$115–$135",
      tier: 1,
      tagline: "One of the most collectible skate silhouettes ever released.",
      relatedSlugs: ["dunk-low", "air-jordan-1", "yeezy-350-v2"],
    },
    {
      slug: "yeezy-350-v2",
      name: "Yeezy Boost 350 V2",
      brand: "Adidas",
      family: "Yeezy",
      silhouette: "Low",
      firstRelease: "2016",
      retailPrice: "$220–$230",
      tier: 1,
      tagline: "A defining modern knit runner that helped shape the hype-era resale market.",
      relatedSlugs: ["yeezy-slide", "yeezy-foam-runner", "ultraboost"],
    },
    {
      slug: "yeezy-slide",
      name: "Yeezy Slide",
      brand: "Adidas",
      family: "Yeezy",
      silhouette: "Slide",
      firstRelease: "2019",
      retailPrice: "$70–$90",
      tier: 1,
      tagline: "Minimalist comfort footwear that became a major resale driver.",
      relatedSlugs: ["yeezy-foam-runner", "yeezy-350-v2"],
    },
    {
      slug: "yeezy-foam-runner",
      name: "Yeezy Foam Runner",
      brand: "Adidas",
      family: "Yeezy",
      silhouette: "Foam clog",
      firstRelease: "2020",
      retailPrice: "$80–$100",
      tier: 1,
      tagline: "A polarizing foam silhouette that became one of the most recognizable comfort shoes.",
      relatedSlugs: ["yeezy-slide", "yeezy-350-v2"],
    },
    {
      slug: "air-max-90",
      name: "Nike Air Max 90",
      brand: "Nike",
      family: "Air Max",
      silhouette: "Low",
      firstRelease: "1990",
      designer: "Tinker Hatfield",
      retailPrice: "$130–$150",
      tier: 2,
      tagline: "A foundational runner with timeless paneling and visible Air heritage.",
      relatedSlugs: ["air-max-95", "air-max-97", "air-force-1"],
    },
    {
      slug: "air-max-95",
      name: "Nike Air Max 95",
      brand: "Nike",
      family: "Air Max",
      silhouette: "Low",
      firstRelease: "1995",
      designer: "Sergio Lozano",
      retailPrice: "$175–$190",
      tier: 2,
      tagline: "A layered runner with unmistakable anatomy-inspired design language.",
      relatedSlugs: ["air-max-90", "air-max-97"],
    },
    {
      slug: "air-max-97",
      name: "Nike Air Max 97",
      brand: "Nike",
      family: "Air Max",
      silhouette: "Low",
      firstRelease: "1997",
      designer: "Christian Tresser",
      retailPrice: "$175–$190",
      tier: 2,
      tagline: "A full-length Air icon with wave lines that became a global lifestyle favorite.",
      relatedSlugs: ["air-max-95", "air-max-90"],
    },
    {
      slug: "air-max-plus",
      name: "Nike Air Max Plus",
      brand: "Nike",
      family: "Air Max",
      silhouette: "Low",
      firstRelease: "1998",
      designer: "Sean McDowell",
      retailPrice: "$175–$190",
      tier: 2,
      tagline: "A tuned-Air runner with aggressive lines and lasting street appeal.",
      relatedSlugs: ["air-max-95", "air-max-97"],
    },
    {
      slug: "air-jordan-3",
      name: "Air Jordan 3",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1988",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$220",
      tier: 2,
      tagline: "The elephant-print classic that helped keep Michael Jordan with Nike.",
      relatedSlugs: ["air-jordan-4", "air-jordan-1", "air-jordan-11"],
    },
    {
      slug: "air-jordan-11",
      name: "Air Jordan 11",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High / Low",
      firstRelease: "1995",
      designer: "Tinker Hatfield",
      retailPrice: "$225–$250",
      tier: 2,
      tagline: "A patent leather legend that remains one of the most coveted Jordan models.",
      relatedSlugs: ["air-jordan-1", "air-jordan-4", "air-jordan-3"],
    },
    {
      slug: "air-jordan-5",
      name: "Air Jordan 5",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1990",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$225",
      tier: 2,
      tagline: "A fighter-jet inspired Jordan with reflective tongue and aggressive styling.",
      relatedSlugs: ["air-jordan-4", "air-jordan-6"],
    },
    {
      slug: "air-jordan-6",
      name: "Air Jordan 6",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1991",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$225",
      tier: 2,
      tagline: "The championship-era Jordan with strong performance heritage and loyal demand.",
      relatedSlugs: ["air-jordan-5", "air-jordan-7"],
    },
    {
      slug: "air-jordan-7",
      name: "Air Jordan 7",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1992",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$215",
      tier: 3,
      tagline: "A Huarache-inspired Jordan tied to the Dream Team era.",
      relatedSlugs: ["air-jordan-6", "air-jordan-8"],
    },
    {
      slug: "air-jordan-8",
      name: "Air Jordan 8",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1993",
      designer: "Tinker Hatfield",
      retailPrice: "$210–$225",
      tier: 3,
      tagline: "A strap-heavy Jordan with bold styling and strong nostalgia appeal.",
      relatedSlugs: ["air-jordan-7", "air-jordan-11"],
    },
    {
      slug: "air-jordan-12",
      name: "Air Jordan 12",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1996",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$225",
      tier: 2,
      tagline: "A luxury-leaning Jordan tied to flu-game history and strong retro demand.",
      relatedSlugs: ["air-jordan-11", "air-jordan-13"],
    },
    {
      slug: "air-jordan-13",
      name: "Air Jordan 13",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High",
      firstRelease: "1997",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$220",
      tier: 3,
      tagline: "A panther-inspired Jordan with strong OG nostalgia.",
      relatedSlugs: ["air-jordan-12", "air-jordan-14"],
    },
    {
      slug: "air-jordan-14",
      name: "Air Jordan 14",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "High / Low",
      firstRelease: "1998",
      designer: "Tinker Hatfield",
      retailPrice: "$200–$220",
      tier: 3,
      tagline: "A Ferrari-inspired Jordan linked to the last-shot era.",
      relatedSlugs: ["air-jordan-13", "air-jordan-12"],
    },
    {
      slug: "new-balance-990v3",
      name: "New Balance 990v3",
      brand: "New Balance",
      family: "990",
      silhouette: "Runner",
      firstRelease: "2012",
      retailPrice: "$185–$210",
      tier: 2,
      tagline: "A comfort-first runner that became a major modern lifestyle staple.",
      relatedSlugs: ["new-balance-2002r", "new-balance-9060"],
    },
    {
      slug: "new-balance-2002r",
      name: "New Balance 2002R",
      brand: "New Balance",
      family: "2000",
      silhouette: "Runner",
      firstRelease: "2010 / retro era resurgence",
      retailPrice: "$140–$160",
      tier: 2,
      tagline: "A retro runner with broad appeal across GRs and collaborations.",
      relatedSlugs: ["new-balance-990v3", "new-balance-9060"],
    },
    {
      slug: "new-balance-9060",
      name: "New Balance 9060",
      brand: "New Balance",
      family: "90X",
      silhouette: "Runner",
      firstRelease: "2022",
      retailPrice: "$150–$180",
      tier: 2,
      tagline: "A futuristic reinterpretation of New Balance heritage design language.",
      relatedSlugs: ["new-balance-2002r", "new-balance-990v3"],
    },
    {
      slug: "asics-gel-kayano-14",
      name: "ASICS Gel-Kayano 14",
      brand: "ASICS",
      family: "Gel-Kayano",
      silhouette: "Runner",
      firstRelease: "2008 / retro resurgence",
      retailPrice: "$150–$180",
      tier: 2,
      tagline: "A retro-tech runner that became one of the strongest non-Nike lifestyle options.",
      relatedSlugs: ["asics-gel-1130", "new-balance-2002r"],
    },
    {
      slug: "asics-gel-1130",
      name: "ASICS Gel-1130",
      brand: "ASICS",
      family: "GEL",
      silhouette: "Runner",
      firstRelease: "2008 / retro resurgence",
      retailPrice: "$100–$120",
      tier: 3,
      tagline: "A value-oriented retro runner with rising relevance in lifestyle circles.",
      relatedSlugs: ["asics-gel-kayano-14"],
    },
    {
      slug: "adidas-superstar",
      name: "Adidas Superstar",
      brand: "Adidas",
      family: "Superstar",
      silhouette: "Low",
      firstRelease: "1969",
      retailPrice: "$95–$110",
      tier: 2,
      tagline: "The shell-toe classic that moved from basketball to music and streetwear.",
      relatedSlugs: ["adidas-samba", "stan-smith"],
    },
    {
      slug: "adidas-samba",
      name: "Adidas Samba",
      brand: "Adidas",
      family: "Samba",
      silhouette: "Low",
      firstRelease: "1950",
      retailPrice: "$100–$120",
      tier: 1,
      tagline: "A terrace classic turned modern fashion staple with powerful lifestyle momentum.",
      relatedSlugs: ["adidas-gazelle", "adidas-superstar"],
    },
    {
      slug: "adidas-gazelle",
      name: "Adidas Gazelle",
      brand: "Adidas",
      family: "Gazelle",
      silhouette: "Low",
      firstRelease: "1966",
      retailPrice: "$100–$120",
      tier: 2,
      tagline: "A suede terrace icon with broad casual and fashion appeal.",
      relatedSlugs: ["adidas-samba", "adidas-superstar"],
    },
    {
      slug: "stan-smith",
      name: "Adidas Stan Smith",
      brand: "Adidas",
      family: "Stan Smith",
      silhouette: "Low",
      firstRelease: "1971",
      retailPrice: "$95–$110",
      tier: 2,
      tagline: "A minimalist tennis classic with global recognition.",
      relatedSlugs: ["adidas-superstar", "air-force-1"],
    },
    {
      slug: "ultraboost",
      name: "Adidas Ultraboost",
      brand: "Adidas",
      family: "Ultraboost",
      silhouette: "Runner",
      firstRelease: "2015",
      retailPrice: "$180–$220",
      tier: 3,
      tagline: "A knit performance runner that became one of Adidas’ most influential modern launches.",
      relatedSlugs: ["yeezy-350-v2", "asics-gel-kayano-14"],
    },
    {
      slug: "converse-chuck-taylor-all-star",
      name: "Converse Chuck Taylor All Star",
      brand: "Converse",
      family: "Chuck Taylor",
      silhouette: "High / Low",
      firstRelease: "1917",
      retailPrice: "$60–$80",
      tier: 2,
      tagline: "An all-time canvas classic with unmatched cultural longevity.",
      relatedSlugs: ["vans-old-skool"],
    },
    {
      slug: "vans-old-skool",
      name: "Vans Old Skool",
      brand: "Vans",
      family: "Old Skool",
      silhouette: "Low",
      firstRelease: "1977",
      retailPrice: "$70–$90",
      tier: 2,
      tagline: "The side-stripe skate classic that remains a casual staple.",
      relatedSlugs: ["converse-chuck-taylor-all-star", "vans-sk8-hi"],
    },
    {
      slug: "vans-sk8-hi",
      name: "Vans Sk8-Hi",
      brand: "Vans",
      family: "Sk8-Hi",
      silhouette: "High",
      firstRelease: "1978",
      retailPrice: "$80–$95",
      tier: 3,
      tagline: "A high-top skate staple with lasting subcultural relevance.",
      relatedSlugs: ["vans-old-skool"],
    },
    {
      slug: "crocs-pollex-clog",
      name: "Crocs Pollex Clog",
      brand: "Crocs",
      family: "Pollex",
      silhouette: "Clog",
      firstRelease: "2021",
      retailPrice: "$85–$95",
      tier: 2,
      tagline: "A comfort-meets-design collaboration line with surprising resale traction.",
      relatedSlugs: ["yeezy-foam-runner"],
    },
    {
      slug: "nike-vomero-5",
      name: "Nike Vomero 5",
      brand: "Nike",
      family: "Vomero",
      silhouette: "Runner",
      firstRelease: "2010 / retro resurgence",
      retailPrice: "$160–$180",
      tier: 2,
      tagline: "A retro runner with strong crossover appeal between performance and lifestyle.",
      relatedSlugs: ["asics-gel-kayano-14", "new-balance-2002r"],
    },
    {
      slug: "nike-cortez",
      name: "Nike Cortez",
      brand: "Nike",
      family: "Cortez",
      silhouette: "Low",
      firstRelease: "1972",
      retailPrice: "$90–$110",
      tier: 3,
      tagline: "A foundational Nike runner with deep historical and cultural roots.",
      relatedSlugs: ["nike-killshot-2", "air-force-1"],
    },
    {
      slug: "nike-killshot-2",
      name: "Nike Killshot 2",
      brand: "Nike",
      family: "Killshot",
      silhouette: "Low",
      firstRelease: "Retro era prominence",
      retailPrice: "$90–$110",
      tier: 3,
      tagline: "A minimalist retro court sneaker with everyday wear appeal.",
      relatedSlugs: ["nike-cortez", "stan-smith"],
    },
    {
      slug: "nike-blazer-mid",
      name: "Nike Blazer Mid",
      brand: "Nike",
      family: "Blazer",
      silhouette: "Mid",
      firstRelease: "1973",
      retailPrice: "$100–$115",
      tier: 2,
      tagline: "A vintage Nike basketball silhouette with strong retro appeal.",
      relatedSlugs: ["nike-blazer-low", "air-force-1"],
    },
    {
      slug: "nike-blazer-low",
      name: "Nike Blazer Low",
      brand: "Nike",
      family: "Blazer",
      silhouette: "Low",
      firstRelease: "1973",
      retailPrice: "$90–$110",
      tier: 3,
      tagline: "A lower-cut version of the classic Blazer with casual versatility.",
      relatedSlugs: ["nike-blazer-mid"],
    },
    {
      slug: "sacai-ldwaffle",
      name: "Sacai x Nike LDWaffle",
      brand: "Nike / sacai",
      family: "LDWaffle",
      silhouette: "Runner",
      firstRelease: "2019",
      retailPrice: "$160–$180",
      tier: 2,
      tagline: "A layered hybrid runner that defined one phase of the collaboration era.",
      relatedSlugs: ["travis-scott-air-jordan-1-low", "nike-vomero-5"],
    },
    {
      slug: "travis-scott-air-jordan-1-low",
      name: "Travis Scott x Air Jordan 1 Low",
      brand: "Jordan Brand",
      family: "Air Jordan 1",
      silhouette: "Low",
      firstRelease: "2019",
      retailPrice: "$150–$170",
      tier: 1,
      tagline: "A reverse-Swoosh collaboration line with some of the strongest modern resale energy.",
      relatedSlugs: ["air-jordan-1", "travis-scott-air-jordan-1-high"],
    },
    {
      slug: "travis-scott-air-jordan-1-high",
      name: "Travis Scott x Air Jordan 1 High",
      brand: "Jordan Brand",
      family: "Air Jordan 1",
      silhouette: "High",
      firstRelease: "2019",
      retailPrice: "$175–$200",
      tier: 1,
      tagline: "A modern grail that became one of the defining AJ1 collaborations of the era.",
      relatedSlugs: ["air-jordan-1", "travis-scott-air-jordan-1-low"],
    },
    {
      slug: "off-white-air-force-1",
      name: "Off-White x Air Force 1",
      brand: "Nike / Off-White",
      family: "Air Force",
      silhouette: "Low",
      firstRelease: "2017",
      retailPrice: "$150–$250",
      tier: 1,
      tagline: "A deconstructed Air Force 1 series with high collector demand and strong market status.",
      relatedSlugs: ["air-force-1", "off-white-blazer"],
    },
    {
      slug: "off-white-blazer",
      name: "Off-White x Nike Blazer",
      brand: "Nike / Off-White",
      family: "Blazer",
      silhouette: "Mid",
      firstRelease: "2017",
      retailPrice: "$130–$150",
      tier: 2,
      tagline: "A deconstructed Blazer collaboration central to the Off-White era.",
      relatedSlugs: ["nike-blazer-mid", "off-white-air-force-1"],
    },
    {
      slug: "dior-air-jordan-1",
      name: "Dior x Air Jordan 1",
      brand: "Dior / Jordan Brand",
      family: "Air Jordan 1",
      silhouette: "High / Low",
      firstRelease: "2020",
      retailPrice: "$2,000+",
      tier: 1,
      tagline: "One of the most exclusive and expensive Jordan collaborations ever released.",
      relatedSlugs: ["air-jordan-1", "travis-scott-air-jordan-1-high"],
    },
    {
      slug: "brooks-ghost",
      name: "Brooks Ghost",
      brand: "Brooks",
      family: "Ghost",
      silhouette: "Runner",
      firstRelease: "Ongoing performance line",
      retailPrice: "$140–$160",
      tier: 3,
      tagline: "A mainstream neutral running shoe known for comfort and consistency.",
      relatedSlugs: ["asics-gel-kayano-14"],
    },
    {
      slug: "hoka-clifton",
      name: "HOKA Clifton",
      brand: "HOKA",
      family: "Clifton",
      silhouette: "Runner",
      firstRelease: "Ongoing performance line",
      retailPrice: "$145–$160",
      tier: 3,
      tagline: "A cushioned running model with broad adoption beyond performance circles.",
      relatedSlugs: ["asics-gel-kayano-14"],
    },
    {
      slug: "hoka-bondi",
      name: "HOKA Bondi",
      brand: "HOKA",
      family: "Bondi",
      silhouette: "Runner",
      firstRelease: "Ongoing performance line",
      retailPrice: "$160–$175",
      tier: 3,
      tagline: "A maximal-cushion runner associated with comfort-first buyers.",
      relatedSlugs: ["hoka-clifton"],
    },
    {
      slug: "salomon-xt-6",
      name: "Salomon XT-6",
      brand: "Salomon",
      family: "XT",
      silhouette: "Trail runner",
      firstRelease: "2013 / lifestyle crossover",
      retailPrice: "$180–$200",
      tier: 2,
      tagline: "A trail-rooted silhouette that broke into fashion and lifestyle markets.",
      relatedSlugs: ["asics-gel-kayano-14", "new-balance-2002r"],
    },
    {
      slug: "salomon-acs-pro",
      name: "Salomon ACS Pro",
      brand: "Salomon",
      family: "ACS",
      silhouette: "Trail runner",
      firstRelease: "Retro / lifestyle crossover",
      retailPrice: "$180–$200",
      tier: 3,
      tagline: "A technical trail shoe embraced by fashion-forward sneaker buyers.",
      relatedSlugs: ["salomon-xt-6"],
    },
    {
      slug: "reebok-club-c-85",
      name: "Reebok Club C 85",
      brand: "Reebok",
      family: "Club C",
      silhouette: "Low",
      firstRelease: "1985",
      retailPrice: "$75–$95",
      tier: 3,
      tagline: "A clean vintage court sneaker with steady casual appeal.",
      relatedSlugs: ["stan-smith", "air-force-1"],
    },
    {
      slug: "reebok-classic-leather",
      name: "Reebok Classic Leather",
      brand: "Reebok",
      family: "Classic",
      silhouette: "Low",
      firstRelease: "1983",
      retailPrice: "$75–$95",
      tier: 3,
      tagline: "A simple leather runner with lasting everyday wear appeal.",
      relatedSlugs: ["reebok-club-c-85"],
    },
    {
      slug: "puma-suede",
      name: "Puma Suede",
      brand: "Puma",
      family: "Suede",
      silhouette: "Low",
      firstRelease: "1968",
      retailPrice: "$75–$90",
      tier: 3,
      tagline: "A heritage court model with strong music and streetwear roots.",
      relatedSlugs: ["adidas-superstar", "vans-old-skool"],
    },
    {
      slug: "puma-palermo",
      name: "Puma Palermo",
      brand: "Puma",
      family: "Palermo",
      silhouette: "Low",
      firstRelease: "1980s / retro revival",
      retailPrice: "$90–$110",
      tier: 3,
      tagline: "A terrace-inspired retro shoe benefiting from casual trend cycles.",
      relatedSlugs: ["adidas-samba", "adidas-gazelle"],
    },
    {
      slug: "on-cloudmonster",
      name: "On Cloudmonster",
      brand: "On",
      family: "Cloud",
      silhouette: "Runner",
      firstRelease: "Modern performance line",
      retailPrice: "$170–$190",
      tier: 3,
      tagline: "A distinctive performance runner with growing everyday visibility.",
      relatedSlugs: ["hoka-clifton"],
    },
    {
      slug: "on-cloud-5",
      name: "On Cloud 5",
      brand: "On",
      family: "Cloud",
      silhouette: "Runner",
      firstRelease: "Modern performance line",
      retailPrice: "$130–$150",
      tier: 3,
      tagline: "A lightweight comfort runner with strong everyday commuter appeal.",
      relatedSlugs: ["on-cloudmonster"],
    },
    {
      slug: "bapesta",
      name: "BAPE STA",
      brand: "BAPE",
      family: "BAPE STA",
      silhouette: "Low",
      firstRelease: "2000",
      retailPrice: "$250–$350",
      tier: 2,
      tagline: "A patent-heavy streetwear icon heavily tied to early-2000s culture.",
      relatedSlugs: ["air-force-1", "bb-sneaker"],
    },
    {
      slug: "bottega-speedster",
      name: "Bottega Veneta Speedster",
      brand: "Bottega Veneta",
      family: "Luxury",
      silhouette: "Low",
      firstRelease: "Luxury fashion line",
      retailPrice: "$700+",
      tier: 3,
      tagline: "A luxury designer sneaker relevant more to fashion buyers than core sneaker resellers.",
      relatedSlugs: [],
    },
    {
      slug: "air-jordan-1-low",
      name: "Air Jordan 1 Low",
      brand: "Jordan Brand",
      family: "Air Jordan 1",
      silhouette: "Low",
      firstRelease: "1985 / retro line evolution",
      retailPrice: "$110–$140",
      tier: 2,
      tagline: "A lower-cut AJ1 variant with broad accessibility and strong casual demand.",
      relatedSlugs: ["air-jordan-1", "air-jordan-1-mid"],
    },
    {
      slug: "air-jordan-1-mid",
      name: "Air Jordan 1 Mid",
      brand: "Jordan Brand",
      family: "Air Jordan 1",
      silhouette: "Mid",
      firstRelease: "Retro line evolution",
      retailPrice: "$120–$140",
      tier: 2,
      tagline: "A controversial but commercially strong Jordan line with mass-market reach.",
      relatedSlugs: ["air-jordan-1", "air-jordan-1-low"],
    },
    {
      slug: "dunk-high",
      name: "Nike Dunk High",
      brand: "Nike",
      family: "Dunk",
      silhouette: "High",
      firstRelease: "1985",
      retailPrice: "$125–$140",
      tier: 2,
      tagline: "A high-top Dunk variant with stronger retro appeal than broad modern demand.",
      relatedSlugs: ["dunk-low", "sb-dunk-low"],
    },
    {
      slug: "new-balance-550",
      name: "New Balance 550",
      brand: "New Balance",
      family: "550",
      silhouette: "Low",
      firstRelease: "1989 / retro resurgence",
      retailPrice: "$110–$130",
      tier: 2,
      tagline: "A retro basketball model that became a clean lifestyle staple.",
      relatedSlugs: ["new-balance-990v3", "new-balance-2002r"],
    },
    {
      slug: "new-balance-530",
      name: "New Balance 530",
      brand: "New Balance",
      family: "530",
      silhouette: "Runner",
      firstRelease: "Retro resurgence",
      retailPrice: "$100–$120",
      tier: 3,
      tagline: "An accessible retro runner with broad casual wear appeal.",
      relatedSlugs: ["new-balance-2002r"],
    },
    {
      slug: "nike-zoom-fly",
      name: "Nike Zoom Fly",
      brand: "Nike",
      family: "Zoom",
      silhouette: "Runner",
      firstRelease: "2017",
      retailPrice: "$160–$180",
      tier: 3,
      tagline: "A performance-minded running silhouette with occasional crossover relevance.",
      relatedSlugs: ["nike-vomero-5"],
    },
    {
      slug: "nike-pegasus",
      name: "Nike Pegasus",
      brand: "Nike",
      family: "Pegasus",
      silhouette: "Runner",
      firstRelease: "1983 / ongoing line",
      retailPrice: "$130–$150",
      tier: 3,
      tagline: "A long-running Nike performance franchise with mainstream visibility.",
      relatedSlugs: ["nike-zoom-fly", "air-max-90"],
    },
    {
      slug: "nike-zoomx-vaporfly",
      name: "Nike ZoomX Vaporfly",
      brand: "Nike",
      family: "ZoomX",
      silhouette: "Runner",
      firstRelease: "2017",
      retailPrice: "$250+",
      tier: 3,
      tagline: "A carbon-plated performance runner more relevant to racing than lifestyle resale.",
      relatedSlugs: ["nike-zoom-fly"],
    },
    {
      slug: "adidas-campus-00s",
      name: "Adidas Campus 00s",
      brand: "Adidas",
      family: "Campus",
      silhouette: "Low",
      firstRelease: "Retro revival",
      retailPrice: "$110–$120",
      tier: 2,
      tagline: "A chunky revival of a classic Adidas line tied to current youth style trends.",
      relatedSlugs: ["adidas-samba", "adidas-gazelle"],
    },
    {
      slug: "nike-shox-r4",
      name: "Nike Shox R4",
      brand: "Nike",
      family: "Shox",
      silhouette: "Runner",
      firstRelease: "2000",
      retailPrice: "$140–$160",
      tier: 2,
      tagline: "A tech-heavy early-2000s runner currently benefiting from Y2K nostalgia.",
      relatedSlugs: ["air-max-plus", "nike-vomero-5"],
    },
    {
      slug: "air-jordan-39",
      name: "Air Jordan 39",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "Performance basketball",
      firstRelease: "Modern line",
      retailPrice: "$190–$210",
      tier: 3,
      tagline: "A current-performance Jordan more relevant for line completeness than resale depth.",
      relatedSlugs: ["air-jordan-38", "air-jordan-1"],
    },
    {
      slug: "air-jordan-38",
      name: "Air Jordan 38",
      brand: "Jordan Brand",
      family: "Air Jordan",
      silhouette: "Performance basketball",
      firstRelease: "Modern line",
      retailPrice: "$180–$200",
      tier: 3,
      tagline: "A modern on-court Jordan entry included for encyclopedia completeness.",
      relatedSlugs: ["air-jordan-39"],
    },
  ];